# jnis2008.github.io
# @jnii2008

title: 我的個人作品集
description: 這是我的 HTML/CSS/JS 練習與作品展示網站
author: jnis2008


url: "https://jnis2008.github.io"
baseurl: "" 

theme: jekyll-theme-minimal

exclude:
  - README.md
  - .gitignore
